// ASC Skills Connect — local-disk file storage (dev stand-in for S3)
//
// Spec section 2.1 calls for "Document Storage — object storage
// (e.g. S3-compatible) for ID copies, CVs, certificates, transcripts,
// portfolio evidence." No real S3/object-storage account exists for this
// project, so this stores on local disk instead — every function here
// takes/returns the same shapes an S3 client would (a caller-opaque
// "key" string, a Buffer), so swapping in a real S3-compatible client
// later means rewriting this one file, not any of its callers in
// server.js. Also happens to satisfy the spec's POPIA in-region hosting
// note trivially, since the disk is wherever this server runs.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const STORAGE_ROOT = path.join(__dirname, "uploads");
fs.mkdirSync(STORAGE_ROOT, { recursive: true });

function keyToPath(key) {
  const fullPath = path.join(STORAGE_ROOT, key);
  // Defense in depth: even though keys are only ever generated by
  // saveFile() below or read back out of the database (never taken
  // directly from a request path param), refuse anything that would
  // resolve outside STORAGE_ROOT.
  if (!fullPath.startsWith(STORAGE_ROOT + path.sep)) throw new Error("Invalid storage key");
  return fullPath;
}

// learnerId/documentType are both already-validated (UUID FK, enum
// CHECK) by the time this is called — safe to use directly in a path.
function saveFile(buffer, learnerId, documentType, originalName) {
  const ext = path.extname(originalName || "").slice(0, 10); // cap a pathological extension length
  const key = `${learnerId}/${documentType}-${crypto.randomUUID()}${ext}`;
  const fullPath = keyToPath(key);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, buffer);
  return key; // stored verbatim in learner_documents.file_url
}

function readFile(key) {
  return fs.readFileSync(keyToPath(key));
}

module.exports = { saveFile, readFile };
